apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_xxx
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: metal_spitt
spec:
  selector:
    app: wordpress
  ports:
    - port: 5050
      targetPort: 5050
  type: LoadBalancer